import type { Metadata } from "next";
// import { Inter } from "next/font/google";
import "./globals.css";
import "animate.css";
import localFont from "@next/font/local";
import Navbar from "@/Components/navbar/page";
import Footer from "@/Components/footer/page";

const montreal = localFont({
  src: "../../public/fonts/montreal-light.ttf",
});

// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/uikit@3.17.11/dist/css/uikit.min.css"
        />

        <script
          defer
          src="https://cdn.jsdelivr.net/npm/uikit@3.17.11/dist/js/uikit.min.js"
        ></script>
        <script
          defer
          src="https://cdn.jsdelivr.net/npm/uikit@3.17.11/dist/js/uikit-icons.min.js"
        ></script>
      </head>
      <body className={montreal.className}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
